[package]
name = "rabbit-auto"
version = "0.1.0"
authors = ["Anicka Burova <anicka.burova@gmail.com>"]
edition = "2018"
licence = "MIT"
description = "Wrappers for lapin publishers and consumers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["tokio_runtime"]
tokio_runtime = ["tokio"]

[dependencies]
anyhow = "1.0.38"
futures = "0.3.12"
lapin = "1.6.6"
lazy_static = "1.4.0"
log = "0.4.14"
tokio = { version = "1.2.0", optional = true, features = ["rt", "time"] }
