[package]
name = "rabbit-auto"
version = "0.2.0"
authors = ["Anicka Burova <anicka.burova@gmail.com>"]
edition = "2018"
licence = "MIT"
description = "Wrappers for lapin publishers and consumers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["tokio_runtime"]
tokio_runtime = ["tokio"]
async_std_runtime = ["async-std"]

[dependencies]
anyhow = "1.0.57"
futures = "0.3.21"
lapin = "2.1.1"
lazy_static = "1.4.0"
log = "0.4.17"
nom = "7.1.1"
tokio = { version = "1.18.2", optional = true, features = ["rt", "time"] }
async-std = { version = "1.11.0", optional = true }
